# **Statistical Learning for Automation Systems**

       
## *Prof. Simone Formentin*

___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python. We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy

## Using NumPy

In [3]:
import numpy as np

In [4]:
np.array([1, 2])

array([1, 2])

# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [9]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [18]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
(my_matrix[1][1])

5

In [19]:
a = np.array(my_matrix)
a[1][1]

5

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [25]:
a = np.zeros((3,1))
a.shape

(3, 1)

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## eye

Creates an identity matrix

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
vect = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [31]:
vect

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [35]:
vect.max()

49

In [36]:
np.max(vect)

49

In [38]:
vect.argmax()

4

In [39]:
vect.min()

2

In [40]:
vect.argmin()

5

In [41]:
vect.shape

(10,)

## Indexing and Selection


In [42]:
vect

array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

In [43]:
vect[2]

41

In [44]:
vect[:3]

array([10, 12, 41])

In [45]:
vect[8:]

array([19, 39])

## Operations

In [50]:
vect1 = np.array([1, 2, 3, 4])
vect2 = np.array([5, 6, 7, 8])

In [51]:
vect1 + vect2

array([ 6,  8, 10, 12])

In [52]:
vect2 - vect1

array([4, 4, 4, 4])

In [54]:
vect1 * vect2

array([ 5, 12, 21, 32])

In [55]:
np.dot(vect1,vect2)

70

In [56]:
vect1 / vect2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [57]:
vect1 ** 2

array([ 1,  4,  9, 16], dtype=int32)