## DATA TYPES
### Numbers

In [8]:
1+1 #simple operation 

2

In [7]:
type(1.0) #function for variable type

float

In [3]:
5 % 2 # modulus operator

1

In [4]:
5 // 2 #integral part of division 

2

In [5]:
(2+ 3) * (5 + 5) #expression 

50

In [9]:
2 * 3
5 % 2 # making two operations in a single cell print only the last one

1

### Variable Assignment

In [13]:
var_name = 2 #Note that after an assignment the notebook don't print the var

In [11]:
x=2
y=3

In [12]:
z = x + y #varibles combinzatioin 

#### Strings

In [14]:
#you can define strings inside double or single ': "string", 'string' (same thing!)
x = 'hello'

print(x, end='') # end option to set the end of the current print instruction, so it does not return in the next line

### Format print

In [16]:
num = 12
name = 'Sam'
print('My number is: {one}, and my name is: {two}'.format(one=num, two=name))

My number is: 12, and my name is: Sam


In [17]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 12, and my name is: Sam


In [19]:
print('My number is: %i, and my name is: %s'%(num,name))

My number is: 12, and my name is: Sam


## Lists

In [20]:
[1, 2, 3] #basic list definition

[1, 2, 3]

In [21]:
['hi', 1, [1,2]] #a list can have different kind of data

['hi', 1, [1, 2]]

In [22]:
char_list = ['a', 'b', 'c']
char_list.append('d') # to add an element to the list

In [24]:
char_list[0] # to access the element i start from index 0

'a'

In [25]:
char_list[1:] #index access from second eleemnt to the last one

['b', 'c', 'd']

In [27]:
char_list[:2] # from first to the second (not include the index 2 element)

['a', 'b']

In [28]:
char_list[-1] #to access the last one element

'd'

In [29]:
char_list[0] = 'overwrite' # to overwrite an element

In [30]:
char_list

['overwrite', 'b', 'c', 'd']

## Booleans

In [32]:
True # it is like 1, true bool var
False # like 0, false bool var

False

In [35]:
bool(3)

True

In [34]:
bool(0)

False

In [36]:
assert (bool(1) == True) # assert rise an error if the comparison made is false

In [37]:
assert (bool(0) == True)

AssertionError: 

## Comparison  and logic operators

## Range fucntion

In [38]:
range(5) # return an object like a list from 0 to 4, usefull for iterating into a list

range(0, 5)

In [39]:
list(range(5)) # to have it like a list

[0, 1, 2, 3, 4]

In [40]:
range(1,5) # to make a list from 1 to 5

range(1, 5)

## if, elif, else Statements

In [41]:
if True: # the if statements is followed by a semicolumn
    print("ok")

ok


In [42]:
if 1<2:
    print("first")
else:
    print("second")

first


In [44]:
if 1==2:
    print("First")
elif 3 == 3:
    print("Middle")
else:
    print("Last")

Middle


# for Loops

In [46]:
for i in range(5): #print number from 0 to 4, so in the range
    print(i)

0
1
2
3
4


In [47]:
list_of_el = ['a', 'b', 'c'] #to access the element of a list
for el in list_of_el:
    print(el)

a
b
c


## while Loops

In [51]:
i = 1
while i < 5:
    print(i)
    i += 1

1
2
3
4



---------------

# NumPy

Linear algebra in python, to make math more efficently!

In [52]:
import numpy as np # the as statement is used to access numpy function with np name

### NumPy Arrays

In [53]:
np.array([1,2])

array([1, 2])

In [54]:
my_list = [1, 2, 3] 

In [55]:
np.array(my_list) #create an array from a python list

array([1, 2, 3])

In [56]:
my_list2 = [1, 2, 'a']

In [57]:
np.array(my_list2)

array(['1', '2', 'a'], dtype='<U21')

In [59]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #matrix as list of list

In [61]:
m = np.array(matrix)

In [63]:
m.shape #built in attributes of np object, to look at the dimension 

(3, 3)

In [64]:
m[1][1] # access element 2,2

5

## Built in methods 

### arange

In [65]:
np.arange(0,10) # array from 0 to 9 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(0, 12, 2) #from 0 to 11 each 2 element

array([ 0,  2,  4,  6,  8, 10])

In [69]:
z = np.zeros(3) #array of size 3 of zero 

In [70]:
z.shape #monodimensional vector

(3,)

In [71]:
z2 = np.zeros((3,1)) #bidimensional array 3x1

In [73]:
z2.shape

(3, 1)

In [75]:
np.zeros((5,5)) # matrix 5x5, vector allocated at first (initialization)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.ones((3,3)) #matrix of ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## eye (identity)

In [77]:
np.eye(4) #identity 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## max, min, ecc

In [78]:
vect = np.array([3, 10, 6, 15, 16, 28, 30])

In [80]:
vect.max() #access the biggest element, class function 

30

In [81]:
vect.argmax() # it return the index of the max element on the array 

6

In [82]:
vect.min() #return the slowest element

3

In [84]:
vect.argmin()

0

In [85]:
np.max(vect) #is the same thing of vect.max()!

30

## Indexing

In [ ]:
#same access notation of normal python list!

In [86]:
vect[:3]

array([ 3, 10,  6])

## Operation

In [87]:
vect1 = np.array([2, 5, 3, 8])

In [88]:
vect2 = np.array([4, 3, 8, 1])

In [89]:
vect1 + vect2 # sum element per element

array([ 6,  8, 11,  9])

In [91]:
vect1 - vect2 #subtraction element wise 

array([-2,  2, -5,  7])

In [92]:
vect1 * vect2 #product element wise

array([ 8, 15, 24,  8])

In [94]:
vect1 / vect2 # division element wise

array([0.5       , 1.66666667, 0.375     , 8.        ])

In [95]:
np.dot(vect1, vect2) # vector product 'dot' (liear algebra)

55

In [97]:
vect1 **2 #square element wise

array([ 4, 25,  9, 64])